### ISSUE TITLE
Is there a way to submit an issue？

### ISSUE THREAD

**Issue by taisuishen** [pevik/ima-evm-utils#1]
I found that url:https://sourceforge.net/p/linux-ima/mailman/linux-ima-devel/ shows this **list is closed and no one can subscribe to it.**

**Comment by pevik** [comment]
https://github.com/mimizohar/ima-evm-utils is the original upstream fork. I'm removing my fork and clone it there.
Also the mailing list is http://vger.kernel.org/vger-lists.html#linux-integrity (archive: https://lore.kernel.org/linux-integrity/)
